// Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
import {
  addIssueToProject,
  getProjectData,
  updateProjectDateField,
  updateProjectSingleSelectField,
  updateProjectTextField,
} from "../services/project-v2-services";
import { PROJECT_FIELD_MAPPINGS } from "./field-mappings";
import { formatDateForGitHub } from "./dates";
import { ProjectV2FieldNode, GraphQLFunction } from "../types/project-v2-types";
import {
  ProjectFieldMapping,
  ProjectFieldType,
  IncidentFieldData,
} from "../types/incident-field-types";
import { getIssue, listIssueComments } from "../services/github-services";
import { extractReplicatedIssueNumber } from "./parsers";
import { OctokitClient, IssueDetails } from "../types/github-types";

/**
 * Shared Helper Functions for Issue Operations
 *
 * This module provides reusable, well-tested functions for replicating, closing,
 * and syncing security incident issues. Functions are designed to be composable
 * and follow the single responsibility principle.
 */

/**
 * Updates all project fields based on the field mappings configuration.
 */
export async function updateAllProjectFields(
  graphql: GraphQLFunction,
  projectId: string,
  itemId: string,
  fields: ProjectV2FieldNode[],
  incidentData: IncidentFieldData,
): Promise<void> {
  const getFieldById = (name: string) =>
    fields.find((field) => field.name === name)?.id;
  const getField = (name: string) =>
    fields.find((field) => field.name === name);

  // Build all update promises based on field mappings
  const updatePromises = PROJECT_FIELD_MAPPINGS.map(
    (mapping: ProjectFieldMapping) => {
      const value = incidentData[mapping.dataKey];

      switch (mapping.fieldType) {
        case ProjectFieldType.TEXT:
          return updateProjectTextField(
            graphql,
            projectId,
            itemId,
            getFieldById(mapping.projectFieldName),
            value,
            mapping.projectFieldName,
          );

        case ProjectFieldType.SINGLE_SELECT:
          return updateProjectSingleSelectField(
            graphql,
            projectId,
            itemId,
            getField(mapping.projectFieldName),
            value,
            mapping.projectFieldName,
          );

        case ProjectFieldType.DATE:
          return updateProjectDateField(
            graphql,
            projectId,
            itemId,
            getFieldById(mapping.projectFieldName),
            formatDateForGitHub(value),
            mapping.projectFieldName,
          );

        default:
          return Promise.resolve();
      }
    },
  );

  await Promise.all(updatePromises);
}

/**
 * Creates a formatted closure notification comment.
 */
export function createClosureComment(
  replicatedIssueUrl: string,
  isOriginalIssue: boolean,
): string {
  if (isOriginalIssue) {
    return (
      `**Incident Closed & Synced**\n\n` +
      `The final state of the incident report has been synced to the centralised dashboard.\n` +
      `The ${replicatedIssueUrl} has been updated and closed.\n\n` +
      `All incident data from the Google Doc has been synchronized to the project board.`
    );
  } else {
    return (
      `**Incident Closed (Automatically generated by GitHub Actions)**\n\n` +
      `This issue has been automatically closed and synchronized with the latest data from the Google Doc.\n` +
      `The incident has been marked as completed on the project board.`
    );
  }
}

/**
 * Creates a formatted reopen notification comment.
 */
export function createReopenComment(
  replicatedIssueUrl: string,
  isOriginalIssue: boolean,
): string {
  if (isOriginalIssue) {
    return `**Incident Reopened**\n\nThe ${replicatedIssueUrl} has been reopened.`;
  } else {
    return `**Incident Reopened (Automatically generated by GitHub Actions)**\n\nOriginal issue has been reopened, so this replicated issue has been reopened as well.`;
  }
}

/**
 * Validates required environment variables are present.
 */
export function validateEnv(requiredVars: Record<string, string>): void {
  const missing = Object.entries(requiredVars)
    .filter(([, value]) => !value)
    .map(([key]) => key);

  if (missing.length > 0) {
    throw new Error(
      `Missing required environment variables: ${missing.join(", ")}`,
    );
  }
}

/**
 * Creates a replication success comment with a hidden tracking ID.
 */
export function createReplicationComment(
  replicatedIssueUrl: string,
  replicatedIssueNumber: number,
): string {
  return (
    `**Issue Replicated Successfully**\n\n` +
    `A replicated ticket containing the parsed document data has been created in the centralised repository:\n` +
    `${replicatedIssueUrl}\n\n` +
    `All incident data has been synchronized to the project board.\n\n` +
    `<!-- REPLICATED_ISSUE_ID: ${replicatedIssueNumber} -->`
  );
}

/**
 * Extracts the replicated issue from the list of comments.
 */
export async function fetchReplicatedIssueContext(
  originClient: OctokitClient,
  targetClient: OctokitClient,
  originOwner: string,
  originRepo: string,
  originIssueNumber: number,
  targetOwner: string,
  targetRepo: string,
  core: any,
): Promise<IssueDetails> {
  core.info(
    "Fetching issue thread comments to find the hidden replicated issue ID...",
  );

  const issueComments = await listIssueComments(
    originClient,
    originOwner,
    originRepo,
    originIssueNumber,
  );

  const replicatedIssueNumber = extractReplicatedIssueNumber(issueComments);

  if (!replicatedIssueNumber) {
    throw new Error(
      "Could not find the replicated issue ID in GitHub Action Bot comments. Aborting sync.",
    );
  }

  core.notice(
    `Found replicated issue: #${replicatedIssueNumber}. Proceeding with final sync.`,
  );

  const replicatedIssue = await getIssue(
    targetClient,
    targetOwner,
    targetRepo,
    replicatedIssueNumber,
  );

  return replicatedIssue;
}

/**
 * Updates the project item status to "Todo" when an issue is reopened.
 */
export async function updateProjectItemStatus(
  graphql: GraphQLFunction,
  owner: string,
  projectNumber: number,
  issueNodeId: string,
): Promise<void> {
  const projectData = await getProjectData(graphql, owner, projectNumber);
  const itemId = await addIssueToProject(graphql, projectData.id, issueNodeId);

  const statusField = projectData.fields.nodes.find(
    (field) => field.name === "Status",
  );

  if (!statusField) {
    throw new Error("Could not find the 'Status' field in the project schema.");
  }

  await updateProjectSingleSelectField(
    graphql,
    projectData.id,
    itemId,
    statusField,
    "Todo",
    "Status",
  );
}
